dist: trusty
sudo: true
script: 'ci/travis.rb'
before_install:
  - gem install bundler -v 1.17.2
rvm:
  - 2.2
  - 2.3
env:
  - "GEM=ar:postgresql"
bundler_args: --path vendor/bundle --without test
services:
  - memcached
